# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef9e1a91157561b9615e8805f9cf72df2c2fd7de7d0054df08a127bd9c30b157cc2f1ee7a2a73ed95074d199cb4f97050f63a43ef8ce8bff3e8c98cab856f0c

test:
  secret_key_base: f270d722a02c56def434f2b1bc4976d0474f635447f928714dc23e569c535e93529a522f91bc612e88846db437395b780dd77222809aaa5441a8df27ff1207ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
